/**
 * Download utilities — browser-native PDF generation via print dialog.
 * No external library needed.
 */

const buildPrintWindow = (title, bodyHtml) => {
    const win = window.open('', '_blank', 'width=900,height=700');
    if (!win) {
        alert('Please allow popups to download PDFs');
        return null;
    }

    win.document.write(`<!DOCTYPE html>
<html>
<head>
<title>${title}</title>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', sans-serif; color: #1a1a1a; padding: 48px; background: #fff; }
    .header { margin-bottom: 32px; border-bottom: 2px solid #1a73e8; padding-bottom: 16px; }
    .header h1 { font-size: 22px; font-weight: 700; color: #1a73e8; margin-bottom: 4px; }
    .header .subtitle { font-size: 13px; color: #5f6368; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 28px; }
    .meta-item { font-size: 13px; }
    .meta-item .label { color: #5f6368; font-weight: 500; text-transform: uppercase; font-size: 10px; letter-spacing: 0.5px; margin-bottom: 2px; }
    .meta-item .value { font-weight: 600; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px; }
    thead { background: #f1f3f4; }
    th { text-align: left; padding: 10px 14px; font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #5f6368; border-bottom: 2px solid #dadce0; }
    td { padding: 10px 14px; border-bottom: 1px solid #f1f3f4; }
    tr:nth-child(even) { background: #fafafa; }
    .total-row { background: #e8f0fe !important; font-weight: 700; }
    .total-row td { border-top: 2px solid #1a73e8; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #dadce0; font-size: 11px; color: #9aa0a6; text-align: center; }
    @media print {
        body { padding: 24px; }
        @page { margin: 1cm; }
    }
</style>
</head>
<body>
${bodyHtml}
<div class="footer">
    Generated by MaintenOps · ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' })} · ${new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
</div>
</body>
</html>`);

    win.document.close();
    // Brief delay so content renders
    setTimeout(() => { win.print(); }, 400);
    return win;
};

const fmtCurrency = (v) => `₹${Number(v ?? 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const fmtDate = (d) => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: '2-digit', year: 'numeric' }) : '—';

/**
 * Download the User Material List (quotation) as PDF
 * @param {Object} request — request object with metadata
 * @param {Array} materials — array of material items
 */
export const downloadQuotationPDF = (request, materials = []) => {
    const totalCost = materials.reduce((sum, m) => sum + Number(m.totalPrice ?? m.estimatedCost ?? 0), 0);

    const rows = materials.map((m, i) => `
        <tr>
            <td>${i + 1}</td>
            <td>${m.materialName || m.name || '—'}</td>
            <td>${m.specificationText || m.specification || '—'}</td>
            <td style="text-align:right">${m.quantity ?? '—'} ${m.unit || ''}</td>
            <td>${m.vendorName || m.vendor?.name || '—'}</td>
            <td style="text-align:right">${fmtCurrency(m.unitPrice ?? m.ratePerUnit ?? 0)}</td>
            <td style="text-align:right">${fmtCurrency(m.totalPrice ?? m.estimatedCost ?? 0)}</td>
        </tr>
    `).join('');

    const bodyHtml = `
        <div class="header">
            <h1>Quotation — User Material List</h1>
            <div class="subtitle">Request #${request.requestNumber || request.id}</div>
        </div>

        <div class="meta-grid">
            <div class="meta-item"><div class="label">Requester</div><div class="value">${request.requesterName || '—'}</div></div>
            <div class="meta-item"><div class="label">Department</div><div class="value">${request.organizationDepartmentName || request.dept || '—'}</div></div>
            <div class="meta-item"><div class="label">Service Dept</div><div class="value">${request.serviceDepartmentName || '—'}</div></div>
            <div class="meta-item"><div class="label">Request Date</div><div class="value">${fmtDate(request.createdAt || request.date)}</div></div>
            <div class="meta-item"><div class="label">Required Date</div><div class="value">${fmtDate(request.requiredDate)}</div></div>
            <div class="meta-item"><div class="label">Status</div><div class="value">${(request.status || '').replace(/_/g, ' ')}</div></div>
        </div>

        <div style="margin-bottom:8px;font-size:14px;font-weight:600;">Description</div>
        <div style="font-size:13px;margin-bottom:24px;color:#3c4043;">${request.itemDescription || '—'}</div>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Material</th>
                    <th>Specification</th>
                    <th style="text-align:right">Qty</th>
                    <th>Vendor</th>
                    <th style="text-align:right">Rate</th>
                    <th style="text-align:right">Total</th>
                </tr>
            </thead>
            <tbody>
                ${rows}
                <tr class="total-row">
                    <td colspan="6" style="text-align:right">Grand Total</td>
                    <td style="text-align:right">${fmtCurrency(totalCost)}</td>
                </tr>
            </tbody>
        </table>
    `;

    buildPrintWindow(`Quotation_${request.requestNumber || request.id}`, bodyHtml);
};

/**
 * Download a single vendor's aggregated purchase list as PDF
 * @param {string} vendorName
 * @param {Array} items — array of purchase list items for this vendor
 */
export const downloadVendorListPDF = (vendorName, items = []) => {
    const totalCost = items.reduce((sum, m) => sum + Number(m.totalPrice ?? m.estimatedCost ?? m.totalQuantity * (m.ratePerUnit ?? 0) ?? 0), 0);

    const rows = items.map((m, i) => `
        <tr>
            <td>${i + 1}</td>
            <td>${m.materialName || m.name || '—'}</td>
            <td>${m.specificationText || '—'}</td>
            <td style="text-align:right">${m.totalQuantity ?? m.quantity ?? '—'} ${m.unit || ''}</td>
            <td>${m.requestNumber || m.requestId || '—'}</td>
            <td style="text-align:right">${fmtCurrency(m.ratePerUnit ?? m.unitPrice ?? 0)}</td>
            <td style="text-align:right">${fmtCurrency(m.totalPrice ?? m.estimatedCost ?? 0)}</td>
            <td style="text-align:center">${m.isPurchased || m.status === 'PROCURED' ? '✅' : '⏳'}</td>
        </tr>
    `).join('');

    const bodyHtml = `
        <div class="header">
            <h1>Vendor Purchase List</h1>
            <div class="subtitle">${vendorName}</div>
        </div>

        <div class="meta-grid">
            <div class="meta-item"><div class="label">Vendor</div><div class="value">${vendorName}</div></div>
            <div class="meta-item"><div class="label">Total Items</div><div class="value">${items.length}</div></div>
            <div class="meta-item"><div class="label">Pending</div><div class="value">${items.filter(i => !i.isPurchased && i.status !== 'PROCURED').length} items</div></div>
            <div class="meta-item"><div class="label">Generated</div><div class="value">${fmtDate(new Date())}</div></div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Material</th>
                    <th>Specification</th>
                    <th style="text-align:right">Qty</th>
                    <th>Request</th>
                    <th style="text-align:right">Rate</th>
                    <th style="text-align:right">Total</th>
                    <th style="text-align:center">Status</th>
                </tr>
            </thead>
            <tbody>
                ${rows}
                <tr class="total-row">
                    <td colspan="6" style="text-align:right">Grand Total</td>
                    <td style="text-align:right">${fmtCurrency(totalCost)}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    `;

    buildPrintWindow(`VendorList_${vendorName.replace(/\s+/g, '_')}`, bodyHtml);
};
